Repository jannomeister/resume, pull requests merged in 2020-08, with the labels that each got.

#5 feat(favicon): updated favicon
  public/favicon.ico
Labels: enhancement

#6 feat: convert all class-based component to function-based
  public/resumeData.json
  src/App.js
  src/Components/About.js
  src/Components/Contact.js
  src/Components/Footer.js
  src/Components/Header.js
  src/Components/Portfolio.js
  src/Components/Resume.js
  src/Components/Testimonials.js
Labels: enhancement

#7 add: dark-blur to header img background
  public/css/layout.css
Labels: enhancement, good first issue

#8 chore(readme): improved README
  README.md
Labels: enhancement

#9 release: 0.2.0
  README.md
  package.json
  public/css/layout.css
  public/favicon.ico
  public/resumeData.json
  src/App.js
  src/Components/About.js
  src/Components/Contact.js
  src/Components/Footer.js
  src/Components/Header.js
  src/Components/Portfolio.js
  src/Components/Resume.js
  src/Components/Testimonials.js
Labels: enhancement

#12 fix(header): fixed missing city name
  src/Components/Header.js
Labels: bugfix

#13 chore(readme): fixed website url
  README.md
Labels: documentation, enhancement

#14 release: 0.2.2
  README.md
  package.json
  src/Components/Header.js
Labels: release

#17 feat(portfolio): added quote randomizer
  public/images/portfolio/pathfinder.png
  public/images/portfolio/quote-randomizer.png
  public/images/portfolio/resume-website.png
  public/resumeData.json
Labels: enhancement

#18 fix(portfolio): fixed invalid url in resume website project
  public/resumeData.json
Labels: bugfix

#19 release: 0.3.0
  package.json
  public/images/portfolio/pathfinder.png
  public/images/portfolio/quote-randomizer.png
  public/images/portfolio/resume-website.png
  public/resumeData.json
Labels: release
